fix: host verification problem
append ssh-keyscan result to known_hosts to fix host verification problem

diff --git a/.github/workflows/ci-provision.yml b/.github/workflows/ci-provision.yml
--- a/.github/workflows/ci-provision.yml
+++ b/.github/workflows/ci-provision.yml
@@ -118,7 +118,9 @@ jobs:
               run: |
                 eval `ssh-agent`
                 ssh-add - <<< "${S_KEY}"
-                ssh-keyscan -H -p $PORT_SSH $PUBLIC_IP > /dev/null 2>&1
+                echo "Appending ssh-keyscan result to known-hsots"
+                ssh-keyscan -H -p $PORT_SSH $PUBLIC_IP >> ~/.ssh/known_hosts
+                [[ $? -ne 0 ]] && echo "Warning: Appending ssh-keyscan result failed!"
                 rsync -avzqR script -e "ssh -p ${PORT_SSH}" $USERNAME_VM@$PUBLIC_IP:~/
                 [[ $? -ne 0 ]] && echo "Warning: rsync failed!"
                 ssh -p $PORT_SSH $USERNAME_VM@$PUBLIC_IP "sudo mv script /root"
